### ISSUE TITLE
React-Query 키 등 constants 관련 폴더 구조

### ISSUE THREAD

**Issue by HojinAn** [dev-debris/stock-simulator#20]
Query 키 및 반복되어 사용되는 상수는 `constants` 폴더로 따로 빼서 사용하면 어떨까요

**Comment by akh9804** [comment]
좋은 것 같아요ㅎㅎ

파일명 형태도 정하면 좋을 것 같아요. 저는 개인적으로 `*.const.ts` 형태를 선호하는데, 다른 분들은 어떠신가염
