### ISSUE TITLE
빈 화면 뜨는 거 다른 노트북으로 해도 똑같은데

### ISSUE THREAD

**Issue by SunNacho** [dev-debris/stock-simulator#23]
![image](https://user-images.githubusercontent.com/105419350/222968460-30b43bf4-fc4a-491f-82d9-e11cba530c1b.png)
이렇게 빈 화면 뜨는 거 똑같네요. 클론하고 나서 yarn install말고 따로 해줘야 하는 것이 있을까요? 타입스크립트 라이브러리를 제가 따로 설치를 안 해서 그런 걸까요? 
![image](https://user-images.githubusercontent.com/105419350/222968525-7b5cbd91-7f8f-4357-8bb0-a0eb099858ee.png)
화면처럼 return에 그냥 34같이 span하나 넣어봤는데 화면엔 아무것도 뜨지 않습니다 ㅜ,ㅜ 맥북이랑 똑같은 상태

**Comment by akh9804** [comment]
찾아보니 현재 코드를 바로 반영하려면 `next dev` 명령어를 실행해야 하네요.

`next start`는 빌드된 파일을 실행하는 거라 `next build`를 실행하고 나서 실행해야 변경한 코드가 반영이 되는 것 같아요. `yarn dev` 명령어로 실행하면 화면에 바로 반영될 거에요.

**Comment by SunNacho** [comment]
와 드디어 해결됐습니다. 여윽시~~ 믿고 있었다구
