### ISSUE TITLE
하위  컴포넌트로 prop전달하는 방법

### ISSUE THREAD

**Issue by SunNacho** [dev-debris/stock-simulator#36]
![image](https://user-images.githubusercontent.com/105419350/227255227-be9b6507-8983-4d3d-97a3-cc81769bf3d7.png)
사진처럼 favorites(boolean)을 하위 컴포넌트로 보내주고 싶은데요

![image](https://user-images.githubusercontent.com/105419350/227255441-f08caaac-c41e-4d28-9a0c-061c2f64c8bf.png)

사진의 파라미터 값에 어떻게 적어주어야 하나요?
`function StockListItem({ticker}: StockListItemProp, favorites)` 이런 식으로 넣으면 안되던데..
혹은 `function StockListItem({ticker}: StockListItemProp, {favorites})` 이런 식으로 넣어도 안되더라구요

**Comment by akh9804** [comment]
props가 추가되는 것이니까 먼저 StockListItemProp 타입을 수정해야 해요

```ts
interface StockListItemProp {
  ...
  favorites: boolean;
}
```

그 다음 구조 분해 할당으로 ticker와 함께 가져오면 됩니당

```ts
function StockListItem({ticker, favorites}: StockListItemProp) {}
```

**Comment by SunNacho** [comment]
아...이렇게 해야하는군요 감사합니다
